# Generated by Django 2.2.16 on 2020-09-16 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('status', models.PositiveIntegerField(choices=[(1, '出货'), (0, '测试')], default=1, verbose_name='状态')),
                ('is_nav', models.BooleanField(default=False, verbose_name='是否为导航')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='客户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='Pdaq',
            fields=[
                ('ip', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='IP地址')),
                ('desc', models.CharField(blank=True, max_length=1024, verbose_name='摘要')),
                ('ICCID', models.CharField(max_length=128, verbose_name='ICCID')),
                ('USB', models.CharField(max_length=128, verbose_name='USB速率')),
                ('comm', models.CharField(max_length=128, verbose_name='4G速率')),
                ('GPS', models.CharField(max_length=128, verbose_name='GPS速率')),
                ('serial_number', models.CharField(max_length=128, verbose_name='序列号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('category', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='my_app.Category', verbose_name='分类')),
                ('custom', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='my_app.Custom', verbose_name='客户')),
            ],
            options={
                'verbose_name': 'pdaq',
                'verbose_name_plural': 'pdaq',
            },
        ),
    ]
