# Generated by Django 2.2.16 on 2020-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200916_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdaq',
            name='custom_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='客户IP'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '删除'), (1, '正常')], default=1, verbose_name='状态'),
        ),
    ]
