# Generated by Django 2.2.16 on 2020-09-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_pdaq_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '正常'), (0, '完结')], default=1, verbose_name='客户状态'),
        ),
    ]
